--- 
abstract: later
author: Toru Yamaguchi <zigorou@cpan.org>
build_requires: 
  CGI::Application::Plugin::AutoRunmode: 0
  CGI::Application::Plugin::Session: 0
  CGI::Session: 0
  Test::WWW::Mechanize::CGI: 0
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CGI-Application-Plugin-Cache-Adaptive
no_index: 
  directory: 
    - inc
    - t
requires: 
  Attribute::Handlers: 0
  CGI::Application: 0
  Cache::Adaptive: 0
  Carp: 0
  Class::Inspector: 0
  Exporter: 0
version: 0.02
